### ISSUE TITLE
Random binary

### ISSUE THREAD

**Issue by moneypython** [Tanishq-Banyal/toastify#1]
What is the exe binary file in this repo? Is the source code for this available?

**Comment by frak0d** [comment]
Actually I lost the source of that notify.exe

But since it's written in C#, you can use use Jetbrains Dotpeek or some other decompiler to recover 90% of source code.

BTW it's just an interface that takes arguments from command line and passes them to [DesktopToast](https://github.com/emoacht/DesktopToast)
